baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

#theme = 'hugo-book'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

#[caches]
#  [caches.images]
#    dir = ':cacheDir/images'
